# Generated by Django 4.0.5 on 2022-06-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('tax_free_amount', models.IntegerField()),
                ('shopped_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
